packages:
  - "medusa"
  - "medusa/apps/*"
  - "storefront"
overrides:
  "@types/react": "19.0.5"
  "@types/react-dom": "19.0.5"
  "eslint>ajv": "^6.12.4"
  "@eslint/eslintrc>ajv": "^6.12.4"
allowBuilds:
  '@medusajs/telemetry': true
  "@parcel/watcher": true
  '@swc/core': true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
minimumReleaseAgeExclude:
  - '@medusajs/admin-bundler@2.19.0'
  - '@medusajs/admin-sdk@2.19.0'
  - '@medusajs/admin-shared@2.19.0'
  - '@medusajs/admin-vite-plugin@2.19.0'
  - '@medusajs/analytics-local@2.19.0'
  - '@medusajs/analytics-posthog@2.19.0'
  - '@medusajs/analytics@2.19.0'
  - '@medusajs/api-key@2.19.0'
  - '@medusajs/auth-emailpass@2.19.0'
  - '@medusajs/auth-github@2.19.0'
  - '@medusajs/auth-google@2.19.0'
  - '@medusajs/auth-oidc@2.19.0'
  - '@medusajs/auth@2.19.0'
  - '@medusajs/cache-inmemory@2.19.0'
  - '@medusajs/cache-redis@2.19.0'
  - '@medusajs/caching-redis@2.19.0'
  - '@medusajs/caching@2.19.0'
  - '@medusajs/cart@2.19.0'
  - '@medusajs/cli@2.19.0'
  - '@medusajs/core-flows@2.19.0'
  - '@medusajs/currency@2.19.0'
  - '@medusajs/customer@2.19.0'
  - '@medusajs/dashboard@2.19.0'
  - '@medusajs/deps@2.19.0'
  - '@medusajs/draft-order@2.19.0'
  - '@medusajs/eslint-plugin@2.19.0'
  - '@medusajs/event-bus-local@2.19.0'
  - '@medusajs/event-bus-redis@2.19.0'
  - '@medusajs/file-local@2.19.0'
  - '@medusajs/file-s3@2.19.0'
  - '@medusajs/file@2.19.0'
  - '@medusajs/framework@2.19.0'
  - '@medusajs/fulfillment-manual@2.19.0'
  - '@medusajs/fulfillment@2.19.0'
  - '@medusajs/icons@2.19.0'
  - '@medusajs/index@2.19.0'
  - '@medusajs/inventory@2.19.0'
  - '@medusajs/js-sdk@2.19.0'
  - '@medusajs/link-modules@2.19.0'
  - '@medusajs/locking-postgres@2.19.0'
  - '@medusajs/locking-redis@2.19.0'
  - '@medusajs/locking@2.19.0'
  - '@medusajs/medusa@2.19.0'
  - '@medusajs/modules-sdk@2.19.0'
  - '@medusajs/notification-local@2.19.0'
  - '@medusajs/notification-sendgrid@2.19.0'
  - '@medusajs/notification@2.19.0'
  - '@medusajs/orchestration@2.19.0'
  - '@medusajs/order@2.19.0'
  - '@medusajs/payment-stripe@2.19.0'
  - '@medusajs/payment@2.19.0'
  - '@medusajs/pricing@2.19.0'
  - '@medusajs/product@2.19.0'
  - '@medusajs/promotion@2.19.0'
  - '@medusajs/query@2.19.0'
  - '@medusajs/rbac@2.19.0'
  - '@medusajs/region@2.19.0'
  - '@medusajs/sales-channel@2.19.0'
  - '@medusajs/search-local@2.19.0'
  - '@medusajs/search@2.19.0'
  - '@medusajs/settings@2.19.0'
  - '@medusajs/stock-location@2.19.0'
  - '@medusajs/store@2.19.0'
  - '@medusajs/tax@2.19.0'
  - '@medusajs/telemetry@2.19.0'
  - '@medusajs/test-utils@2.19.0'
  - '@medusajs/translation@2.19.0'
  - '@medusajs/types@2.19.0'
  - '@medusajs/ui@4.2.1'
  - '@medusajs/user@2.19.0'
  - '@medusajs/utils@2.19.0'
  - '@medusajs/workflow-engine-inmemory@2.19.0'
  - '@medusajs/workflow-engine-redis@2.19.0'
  - '@medusajs/workflows-sdk@2.19.0'
